const tableData = {
    selectedData: [
      {
        field: "item_nr",
        header: "item_nr",
        isNumber: false,
        isType: "0",
      },
      {
        field: "customer_nr",
        header: "customer_nr",
        isNumber: false,
        isType: "0",
      },
      {
        field: "Shipto application",
        header: "Shipto application",
        isNumber: false,
        isType: "0",
      },
      {
        field: "Shipto country",
        header: "Shipto country",
        isNumber: false,
        isType: "0",
      },
      {
        field: "Plant City",
        header: "Plant City",
        isNumber: false,
        isType: "0",
      },
      {
        field: "Delivery Month",
        header: "Delivery Month",
        isNumber: false,
        isType: "0",
      },
      {
        field: "Customer Group",
        header: "Customer Group",
        isNumber: false,
        isType: "0",
      },
      {
        field: "Item Genus",
        header: "Item Genus",
        isNumber: false,
        isType: "0",
      },
      {
        field: "Envelope adjustment",
        header: "Envelope adjustment",
        isNumber: false,
        isType: "1",
      },
      {
        field: "Adder",
        header: "Adder",
        isNumber: false,
        isType: "1",
      },
      {
        field: "Multiplier",
        header: "Multiplier",
        isNumber: false,
        isType: "1",
      },
      {
        field: "Override floor",
        header: "Override floor",
        isNumber: false,
        isType: "1",
      },
      {
        field: "Min Floor",
        header: "Min. Floor",
        isNumber: false,
        isType: "1",
      },
      {
        field: "Inflation",
        header: "Inflation",
        isNumber: false,
        isType: "1",
      },
      {
        field: "Modified Floor",
        header: "Modified Floor",
        isNumber: true,
        isType: "2",
      },
      {
        field: "Modified Target",
        header: "Modified Target",
        isNumber: true,
        isType: "2",
      },
      {
        field: "Modified Expert",
        header: "Modified Expert",
        isNumber: true,
        isType: "2",
      },
      {
        field: "No of Impact Guidance",
        header: "No. of Impact Guidance",
        isNumber: true,
        isType: "2",
      },
    ],
    defaultData: [
      {
        item_nr: "All",
        customer_nr: "All",
        "Shipto application": "All",
        "Shipto country": "All",
        "Plant City": "All",
        "Delivery Month": "All",
        "Customer Group": "All",
        "Item Genus": "All",
        "Envelope adjustment": "All",
        Adder: "0",
        Multiplier: "0",
        "Override floor": "0",
        "Min Floor": "0",
        Inflation: "0",
        "Modified Floor": "Non editable",
        "Modified Target": "Non editable",
        "Modified Expert": "Non editable",
        "No of Impact Guidance": "Non editable",
      },
      {
        item_nr: "RS00RF005",
        customer_nr: "All",
        "Shipto application": "All",
        "Shipto country": "All",
        "Plant City": "All",
        "Delivery Month": "All",
        "Customer Group": "All",
        "Item Genus": "All",
        "Envelope adjustment": "All",
        Adder: "0",
        Multiplier: "0",
        "Override floor": "0",
        "Min Floor": "0",
        Inflation: "0",
        "Modified Floor": "Non editable",
        "Modified Target": "Non editable",
        "Modified Expert": "Non editable",
        "No of Impact Guidance": "Non editable",
      },
      {
       item_nr: "RS00RF005",
        customer_nr: "All",
        "Shipto application": "CGL CAN",
        "Shipto country": "All",
        "Plant City": "All",
        "Delivery Month": "All",
        "Customer Group": "All",
        "Item Genus": "All",
        "Envelope adjustment": "All",
        Adder: "0",
        Multiplier: "0",
        "Override floor": "0",
        "Min Floor": "0",
        Inflation: "0",
        "Modified Floor": "Non editable",
        "Modified Target": "Non editable",
        "Modified Expert": "Non editable",
        "No of Impact Guidance": "Non editable",
      },
    ],
    statuses: [
      { label: "All", value: "All" },
      { label: "CGL CAN", value: "CGL CAN" },
      { label: "RS00RF005", value: "RS00RF005" },
    ],
  };
  
  export const playGroundConstants = {
    tableData,
  };
  